export const tagGroupMapping = {
    PLA: "material",
    Basic: "type",
    Anycubic: "brand",
    Plexiwire: "brand",
    White: "color",
    Gray: "color",
    Black: "color",
    Red: "color",
    Blue: "color",
    Green: "color",
    Ironing: "features",
    "No-Ironing": "features",
    Shiny: "features",
    Mat: "features",
    Test: "features",
};